account_id = "4b59b59a6058dce1832781075d4fde9d"
workers_dev = false
compatibility_date = "2022-01-15"

main = "./dist/worker.js"
rules = [
    { type = "ESModule", globs = ["**/*.js"] }
]

[build]
command = "npm run build"

[triggers]
crons = ["0 9 * * *"]

[env.prod]
name = "polyratings-prod-cron"

[dev]
port = 8080
local_protocol = "https"
