type = "javascript"
zone_id = "a7bc6d72d8d7927ad1a49d855cfad6c6" # polyratings.dev
account_id = "4b59b59a6058dce1832781075d4fde9d"
usage = "bundled"
workers_dev = false
compatibility_date = "2022-01-15"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"

[env.prod]
name = "testing-backend"
route = "testing.polyratings.dev/*"
usage = "bundled"
kv_namespaces = [
    { binding = "POLYRATINGS", id = "c6bf2730306a4e65bb8aa7412ae6f250", preview_id = "1c0b9ffba23c46f2928b7af696de1862"}
]

[env.beta]
name = "testing-backend-beta"
route = "beta-test.polyratings.dev/*"
usage = "bundled"
kv_namespaces = [
    { binding = "POLYRATINGS", id = "1c0b9ffba23c46f2928b7af696de1862", preview_id = "1c0b9ffba23c46f2928b7af696de1862"}
]

[dev]
port = 8080
local_protocol = "https"
