name: Continuous Integration and Deployment

on:
    pull_request:
    push:
        branches:
            - master
            - beta

jobs:
    CI_CD:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: "npm"

            - name: Setup Nx
              uses: nrwl/nx-set-shas@v3

            - name: Install Dependencies
              run: npm ci

            - name: Format packages
              run: npx nx format:check

            - name: Lint packages
              run: npx nx affected -t lint --parallel=3

            - name: Build Packages
              run: npx nx affected -t build --parallel=3

            - name: Test Packages
              run: npx nx affected -t test --parallel=3 --configuration=ci

            - name: Deploy Prod
              if: github.ref == 'refs/heads/master'
              env:
                  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
              run: npx nx affected -t deploy:prod

            - name: Deploy Beta
              if: github.ref == 'refs/heads/beta'
              env:
                  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
              run: npx nx affected -t deploy:beta
