name: Continuous Integration and Deployment

on:
  pull_request:
  push:
    branches:
      - master
      - beta

env:
  NX_BRANCH: ${{ github.event.number || github.ref_name }}
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  Integration_And_Deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout [Pull Request]
        if: ${{ github.event_name == 'pull_request' }}
        with:
          # By default, PRs will be checked-out based on the Merge Commit, but we want the actual branch HEAD.
          ref: ${{ github.event.pull_request.head.sha }}
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0

      - uses: actions/checkout@v3
        name: Checkout [Default Branch]
        if: ${{ github.event_name != 'pull_request' }}
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0

      # Set node/npm/yarn versions using volta
      - uses: volta-cli/action@v4
        with:
          package-json-path: "${{ github.workspace }}/package.json"

      - name: Use the package manager cache if available
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Install Top Level Dependencies
        run: npm ci

      - name: Lint packages
        run: npm run lint

      - name: Build Packages
        run: npm run build

      - name: Test Packages
        run: npm run test

      - name: Deploy Prod
        if: github.ref == 'refs/heads/master'
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: NX_CLOUD_DISTRIBUTED_EXECUTION=false npm run deploy:prod

      - name: Deploy Beta
        if: github.ref == 'refs/heads/beta'
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: NX_CLOUD_DISTRIBUTED_EXECUTION=false npm run deploy:beta
